apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    owner: Emmanuel Pius-Ogiji
    app: k8s-deploy
  name: k8s-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      owner: Emmanuel Pius-Ogiji
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        owner: Emmanuel Pius-Ogiji
        app: k8s-deploy
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources: {}
status: {}