apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    owner: EPO
    app: k8s-deploy
  name: k8s-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      owner: EPO
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        owner: EPO
        app: k8s-deploy
    spec:
      serviceAccountName: service-user
      securityContext:
        runAsUser: 1000
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html
        readinessProbe:
          exec:
            command:
              - cat
              - /usr/share/nginx/html/index.html
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
      volumes:
      - name: config-volume
        configMap:
           name: html-config
status: {}