apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">

    <body>

    <h2 align="center">Welcome to Emmanuel's Kubernetes exercise!</h2>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: html-config
