apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-deploy
    owner: EPO
  name: k8s-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    owner: EPO
  type: LoadBalancer
status:
  loadBalancer: {}
